schema = 1
cname = "rust.pkg.re"
download = "https://rust.pkg.re/crates/{sha256-checksum}.crate"
cargo-version = "1.95.0"

[[registries]]
name = "core"
index = "sparse+https://rust.pkg.re/core/"
may-depend-on = ["core"]

[[registries]]
name = "matrix"
index = "sparse+https://rust.pkg.re/matrix/"
may-depend-on = ["core", "matrix"]

[[registries]]
name = "pkgre"
index = "sparse+https://rust.pkg.re/pkgre/"
may-depend-on = ["core", "matrix", "pkgre"]
