schema = 1
registry = "pkgre"

[[packages]]
name = "pkgre-indexer"
version = "0.1.1"
archive_sha256 = "3257df14bc1ae9d6f2eb99d5db90e5d2a9fbc13c870044c9db5ba89bcc0b96a2"
index_record_sha256 = "b12f0350b65d153f4073d2090dadbbfd497e5746315872d1230d530fc8e46f92"
yanked = false

[packages.source]
kind = "git-tag"
repository = "https://github.com/pkgre/pkgre"
tag = "indexer/v0.1.1"
commit = "27d4cf7c657ef72283f9c61ec0c8ea572ed548d3"
package = "pkgre-indexer"
subdir = "indexer"
